In [125]:
import pandas as pd
man = pd.read_csv('man.csv', encoding = 'cp949')
men_y = man['target_solo']
men_X = man[man.columns[:39]]
woman = pd.read_csv('woman.csv', encoding = 'cp949')
women_y = woman['target_solo']
women_X = woman[woman.columns[:39]]

# 변수 선택

### 남성

In [224]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

clf_tr = DecisionTreeClassifier(random_state = 0)
clf_tr.fit(men_X, men_y)
man_vi = pd.DataFrame({'col': men_X.columns, 'vi': clf_tr.feature_importances_})
man_vi.sort_values('vi', ascending = False)[:10]

col        vi
20              accessory_ring  0.154089
14               participation  0.090385
13                    charging  0.063655
0                        grade  0.060143
17  after_finish_lecture_강의실나감  0.048129
15                  drowsiness  0.047692
30       standard_style_street  0.046821
3                      exit_no  0.044399
35            campus_style_스트릿  0.041661
38                   phonecase  0.035814

In [228]:
clf_tr = DecisionTreeClassifier(random_state = 0)
clf_tr.fit(women_X, women_y)
woman_vi = pd.DataFrame({'col': women_X.columns, 'vi': clf_tr.feature_importances_})
woman_vi.sort_values('vi', ascending = False)[:10]

col        vi
3                   exit_no  0.115041
15               drowsiness  0.100675
24       how_wear_accessory  0.091379
4               position_전방  0.069610
12      phone_position_화면아래  0.048564
37       campus_style_편안한복장  0.044998
7          beside_friend_no  0.044282
27                color_yes  0.040772
13                 charging  0.033581
32  standard_style_training  0.031250

In [248]:
man_vlist = ['accessory_ring', 'participation', 'grade', 'drowsiness',
             'glasses_안경착용', 'phonecase', 'after_finish_lecture_강의실나감']
temp_men = men_X[man_vlist]

clf_tr = DecisionTreeClassifier(random_state = 0)
clf_tr.fit(temp_men, men_y)
man_vi = pd.DataFrame({'col': temp_men.columns, 'vi': clf_tr.feature_importances_})
man_vi.sort_values('vi', ascending = False)

col        vi
2                       grade  0.256461
0              accessory_ring  0.183729
1               participation  0.177563
3                  drowsiness  0.158457
5                   phonecase  0.087361
4                glasses_안경착용  0.072573
6  after_finish_lecture_강의실나감  0.063856

In [249]:
auto_competition(temp_men, men_y, method = 'accuracy')


Using scaled data 

[Logistic Regression] accuracy score: 0.6790
[kNN] accuracy score: 0.7672
[Decision Tree] accuracy score: 0.6652
[SVMLinear] accuracy score: 0.6883
[SVMRbf] accuracy score: 0.7427
[SGD] accuracy score: 0.6415
[Naive Bayes] accuracy score: 0.6828
[Random Forest] accuracy score: 0.7066

Using row data 

[Logistic Regression] accuracy score: 0.6888
[kNN] accuracy score: 0.6878
[Decision Tree] accuracy score: 0.6753
[SVMLinear] accuracy score: 0.6833
[SVMRbf] accuracy score: 0.7186
[SGD] accuracy score: 0.6094
[Naive Bayes] accuracy score: 0.7033
[Random Forest] accuracy score: 0.6918


In [264]:
woman_vlist = ['exit_no', 'how_wear_accessory', 'position_전방', 'phone_position_화면아래',
               'drowsiness', 'accessory_ring', 'campus_style_편안한복장', 'color_yes']
temp_woman = women_X[woman_vlist]

clf_tr = DecisionTreeClassifier(random_state = 0)
clf_tr.fit(temp_woman, women_y)
woman_vi = pd.DataFrame({'col': temp_woman.columns, 'vi': clf_tr.feature_importances_})
woman_vi.sort_values('vi', ascending = False)

col        vi
1   how_wear_accessory  0.352449
0              exit_no  0.175062
4           drowsiness  0.148706
2          position_전방  0.092441
7            color_yes  0.069544
3  phone_position_화면아래  0.061211
6   campus_style_편안한복장  0.059757
5       accessory_ring  0.040831

In [265]:
auto_competition(temp_woman, women_y, method = 'accuracy')


Using scaled data 

[Logistic Regression] accuracy score: 0.7289
[kNN] accuracy score: 0.6951
[Decision Tree] accuracy score: 0.7154
[SVMLinear] accuracy score: 0.7264
[SVMRbf] accuracy score: 0.7444
[SGD] accuracy score: 0.6387
[Naive Bayes] accuracy score: 0.6941
[Random Forest] accuracy score: 0.7264

Using row data 

[Logistic Regression] accuracy score: 0.7088
[kNN] accuracy score: 0.6800
[Decision Tree] accuracy score: 0.7106
[SVMLinear] accuracy score: 0.7264
[SVMRbf] accuracy score: 0.6730
[SGD] accuracy score: 0.5994
[Naive Bayes] accuracy score: 0.7364
[Random Forest] accuracy score: 0.7409


In [266]:
men_X = men_X[man_vlist]
women_X = women_X[woman_vlist]

In [268]:
man = {'X': men_X, 'y': men_y}
woman = {'X': women_X, 'y': women_y}

In [271]:
import pickle
f = open('man_data.pkl', 'wb')
pickle.dump(man, f)
f.close()

f = open('woman_data.pkl', 'wb')
pickle.dump(woman, f)
f.close()

# 알고리즘 비교

In [272]:
import pickle

f = open('man_data.pkl', 'rb')
man = pickle.load(f)
f.close()
men_X = man['X']
men_y = man['y']

f = open('woman_data.pkl', 'rb')
woman = pickle.load(f)
f.close()
women_X = woman['X']
women_y = woman['y']

In [273]:
from auto_competition import auto_competition

In [274]:
# 남성 데이터
auto_competition(men_X, men_y, method = 'accuracy')


Using scaled data 

[Logistic Regression] accuracy score: 0.6790
[kNN] accuracy score: 0.7672
[Decision Tree] accuracy score: 0.6657
[SVMLinear] accuracy score: 0.6883
[SVMRbf] accuracy score: 0.7427
[SGD] accuracy score: 0.6380
[Naive Bayes] accuracy score: 0.6828
[Random Forest] accuracy score: 0.7364

Using row data 

[Logistic Regression] accuracy score: 0.6888
[kNN] accuracy score: 0.6878
[Decision Tree] accuracy score: 0.6805
[SVMLinear] accuracy score: 0.6833
[SVMRbf] accuracy score: 0.7186
[SGD] accuracy score: 0.5838
[Naive Bayes] accuracy score: 0.7033
[Random Forest] accuracy score: 0.7219


# 남성 솔로 판별기

## GridSearch CV

In [276]:
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
import numpy as np

In [402]:
param = [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 2, 5, 10, 100]
weight = {'solo': 1, 'couple': 1.5}
for p in param:
    pipe_svc = Pipeline([('scaler', StandardScaler()),
                 ('clf_svc', SVC(kernel = 'rbf', C = p, tol = 0.1, probability = True, class_weight = weight))])
    cvs = cross_val_score(pipe_svc, men_X, y = men_y, cv = 10)
    mean = np.mean(cvs)
    std = np.std(cvs)
    print('C: %s  ->  %0.4f  +/- %0.4f' % (p, mean, std))

C: 0.001  ->  0.4771  +/- 0.0077
C: 0.005  ->  0.4771  +/- 0.0077
C: 0.01  ->  0.4771  +/- 0.0077
C: 0.05  ->  0.4771  +/- 0.0077
C: 0.1  ->  0.5713  +/- 0.0961
C: 0.5  ->  0.7316  +/- 0.1154
C: 1  ->  0.7414  +/- 0.1037
C: 2  ->  0.7477  +/- 0.1217
C: 5  ->  0.7637  +/- 0.0971
C: 10  ->  0.7487  +/- 0.1039
C: 100  ->  0.7116  +/- 0.0724


In [403]:
from sklearn.metrics import confusion_matrix
idx = np.random.choice(range(len(men_X)), 20)
pipe_svc = Pipeline([('scaler', StandardScaler()),
                 ('clf_svc', SVC(kernel = 'rbf', C = 5, tol = 0.1, probability = True, class_weight = weight))])
pipe_svc.fit(men_X.iloc[-idx], men_y.iloc[-idx])
pred = pipe_svc.predict(men_X.iloc[idx])
confusion_matrix(pred, men_y.iloc[idx])

array([[8, 2],
       [4, 6]])

In [279]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
import numpy as np

for k in range(1, 21):
    pipe_knn = Pipeline([('scaler', StandardScaler()),
                     ('clf_knn', KNeighborsClassifier(n_neighbors = k))])
    print(k, np.mean(cross_val_score(pipe_knn, men_X, y = men_y, cv = 10)))

1 0.716077694236
2 0.664448621554
3 0.742155388471
4 0.674498746867
5 0.767230576441
6 0.757205513784
7 0.712869674185
8 0.711365914787
9 0.693082706767
10 0.691077694236
11 0.702105263158
12 0.691578947368
13 0.702105263158
14 0.706102756892
15 0.670501253133
16 0.700839598997
17 0.680789473684
18 0.690814536341
19 0.677268170426
20 0.696077694236


In [311]:
idx = np.random.choice(range(len(men_X)), 20)
pipe_knn = Pipeline([('scaler', StandardScaler()),
                 ('clf_knn', KNeighborsClassifier(n_neighbors = 5))])
pipe_knn.fit(men_X.iloc[-idx], men_y.iloc[-idx])
pred = pipe_knn.predict(men_X.iloc[idx])
confusion_matrix(pred, men_y.iloc[idx])

array([[4, 1],
       [6, 9]])

In [348]:
from sklearn.ensemble import AdaBoostClassifier

param = [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 2, 5, 10, 100]
for p in param:
    base_clf = SVC(kernel = 'rbf', C = p, tol = 0.1, probability = True)
    pipe_ada = Pipeline([('scaler', StandardScaler()),
                       ('clf', AdaBoostClassifier(base_estimator = base_clf, learning_rate = 0.001, random_state = 0, n_estimators = 500))])
    cvs = np.mean(cross_val_score(pipe_ada, men_X, y = men_y, cv = 10))
    mean = np.mean(cvs)
    std = np.std(cvs)
    print('C: %s  ->  %0.4f  +/- %0.4f' % (p, mean, std))

C: 0.001  ->  0.6981  +/- 0.0000
C: 0.005  ->  0.6981  +/- 0.0000
C: 0.01  ->  0.6981  +/- 0.0000
C: 0.05  ->  0.6928  +/- 0.0000
C: 0.1  ->  0.6928  +/- 0.0000
C: 0.5  ->  0.6923  +/- 0.0000
C: 1  ->  0.7071  +/- 0.0000
C: 2  ->  0.7013  +/- 0.0000
C: 5  ->  0.6870  +/- 0.0000
C: 10  ->  0.6923  +/- 0.0000
C: 100  ->  0.7434  +/- 0.0000


In [328]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

param_max_depth = [1, 3, 5, 10, 50, 100, 200, 500, None]
for d in param_max_depth:
    base_clf = DecisionTreeClassifier(max_depth = d)
    pipe_ada = Pipeline([('scaler', StandardScaler()),
                       ('clf', AdaBoostClassifier(base_estimator = base_clf, learning_rate = 0.001, random_state = 0, n_estimators = 500))])
    cvs = np.mean(cross_val_score(pipe_ada, men_X, y = men_y, cv = 10))
    mean = np.mean(cvs)
    std = np.std(cvs)
    print('max_depth: %s  ->  %0.4f  +/- %0.4f' % (d, mean, std))

max_depth: 1  ->  0.6713  +/- 0.0000
max_depth: 3  ->  0.7369  +/- 0.0000
max_depth: 5  ->  0.7314  +/- 0.0000
max_depth: 10  ->  0.7319  +/- 0.0000
max_depth: 50  ->  0.6918  +/- 0.0000
max_depth: 100  ->  0.6918  +/- 0.0000
max_depth: 200  ->  0.6918  +/- 0.0000
max_depth: 500  ->  0.6918  +/- 0.0000
max_depth: None  ->  0.6918  +/- 0.0000


In [347]:
idx = np.random.choice(range(len(men_X)), 20)
base_clf = DecisionTreeClassifier(max_depth = 3)
pipe_ada = Pipeline([('scaler', StandardScaler()),
                   ('clf', AdaBoostClassifier(base_estimator = base_clf, learning_rate = 0.001, random_state = 0, n_estimators = 500))])

pipe_ada.fit(men_X.iloc[-idx], men_y.iloc[-idx])
pred = pipe_ada.predict(men_X.iloc[idx])
confusion_matrix(pred, men_y.iloc[idx])

array([[6, 7],
       [1, 6]])

In [360]:
idx = np.random.choice(range(len(men_X)), 20)
base_clf = SVC(kernel = 'rbf', C = 100, tol = 0.1, probability = True)
pipe_ada = Pipeline([('scaler', StandardScaler()),
                   ('clf', AdaBoostClassifier(base_estimator = base_clf, learning_rate = 0.001, random_state = 0, n_estimators = 500))])

pipe_ada.fit(men_X.iloc[-idx], men_y.iloc[-idx])
pred = pipe_ada.predict(men_X.iloc[idx])
confusion_matrix(pred, men_y.iloc[idx])

array([[ 6,  2],
       [ 1, 11]])

In [284]:
men_X.columns

Index(['accessory_ring', 'participation', 'grade', 'drowsiness',
       'glasses_안경착용', 'phonecase', 'after_finish_lecture_강의실나감'],
      dtype='object')

In [282]:
import pandas as pd

In [409]:
data = {'accessory_ring': 0, 'participation': 5, 'grade': 4, 'drowsiness': 2, 'glasses_안경착용': 0,
        'phonecase': 1, 'after_finish_lecture_강의실나감': 1}
data = pd.DataFrame(data, index = ['target'])
pipe_svc = Pipeline([('scaler', StandardScaler()),
                 ('clf_svc', SVC(kernel = 'rbf', C = 10, tol = 0.1, probability = True))])
pipe_knn = Pipeline([('scaler', StandardScaler()),
                 ('clf_knn', KNeighborsClassifier(n_neighbors = 5))])
base_clf = DecisionTreeClassifier(max_depth = 3)
pipe_ada = Pipeline([('scaler', StandardScaler()),
                   ('clf', AdaBoostClassifier(base_estimator = base_clf, learning_rate = 0.001, random_state = 0, n_estimators = 500))])
pipe_svc.fit(men_X, men_y)
pipe_knn.fit(men_X, men_y)
pipe_ada.fit(men_X, men_y)
print(pipe_svc.predict(data))
print(pipe_knn.predict_proba(data))
print(pipe_ada.predict_proba(data))

['couple']
[[ 0.2  0.8]]
[[ 0.26916952  0.73083048]]


In [410]:
pipe_svc = Pipeline([('scaler', StandardScaler()),
                 ('clf_svc', SVC(kernel = 'rbf', C = 10, tol = 0.1, probability = True))])
pipe_svc.fit(men_X, men_y)

Pipeline(steps=[('scaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('clf_svc', SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.1, verbose=False))])

## Save

In [413]:
import pickle

man_data = {'X': men_X, 'y': men_y}

f = open('man_data.pkl', 'wb')
pickle.dump(man_data, f)
f.close()

In [414]:
f = open('men_clf.pkl', 'wb')
pickle.dump(pipe_svc, f)
f.close()

# 여성 솔로 판별기

In [415]:
# 여성 데이터
auto_competition(women_X, women_y, method = 'accuracy')


Using scaled data 

[Logistic Regression] accuracy score: 0.7289
[kNN] accuracy score: 0.6951
[Decision Tree] accuracy score: 0.7206
[SVMLinear] accuracy score: 0.7264
[SVMRbf] accuracy score: 0.7444
[SGD] accuracy score: 0.5811
[Naive Bayes] accuracy score: 0.6941
[Random Forest] accuracy score: 0.7159

Using row data 

[Logistic Regression] accuracy score: 0.7088
[kNN] accuracy score: 0.6800
[Decision Tree] accuracy score: 0.7154
[SVMLinear] accuracy score: 0.7264
[SVMRbf] accuracy score: 0.6730
[SGD] accuracy score: 0.5943
[Naive Bayes] accuracy score: 0.7364
[Random Forest] accuracy score: 0.7206


In [416]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
import numpy as np

In [417]:
clf_tr = DecisionTreeClassifier()
clf_tr.fit(women_X, women_y)
np.mean(cross_val_score(clf_tr, women_X, y = women_y, cv = 10))

0.7148496240601504

## GridSearch CV

In [424]:
param_max_depth = [1, 3, 5, 10, 50, 100, 200, 500, None]
for d in param_max_depth:
    pipe_tr = Pipeline([('scaler', StandardScaler()),
                         ('clf', DecisionTreeClassifier(criterion = 'entropy', max_depth = d))])
    cvs = cross_val_score(pipe_tr, women_X, y = women_y, cv = 10)
    mean = np.mean(cvs)
    std = np.std(cvs)
    print('max_depth: %s  ->  %0.4f  +/- %0.4f' % (d, mean, std))

max_depth: 1  ->  0.5184  +/- 0.0579
max_depth: 3  ->  0.7455  +/- 0.0627
max_depth: 5  ->  0.7199  +/- 0.0895
max_depth: 10  ->  0.7093  +/- 0.0630
max_depth: 50  ->  0.7001  +/- 0.1102
max_depth: 100  ->  0.7101  +/- 0.0946
max_depth: 200  ->  0.7001  +/- 0.1102
max_depth: 500  ->  0.7144  +/- 0.1059
max_depth: None  ->  0.7048  +/- 0.1055


In [425]:
from sklearn.ensemble import RandomForestClassifier

param_max_depth = [1, 3, 5, 10, 50, 100, None]
param_n_estimators = [1, 5, 10, 50, 100]
for d in param_max_depth:
    for e in param_n_estimators:
        for mf in ['sqrt', 'log2', None]:
            pipe_rf = Pipeline([('scaler', StandardScaler()),
                                ('clf', RandomForestClassifier(criterion = 'entropy',
                                                                max_depth = d,
                                                                n_estimators = e, 
                                                                max_features = mf,
                                                                random_state = 0, n_jobs = -1))])
            cvs = cross_val_score(pipe_rf, women_X, y = women_y, cv = 10)
            mean = np.mean(cvs)
            std = np.std(cvs)
            print('max_depth: %s / n_estimators: %s / %s ->  %0.4f  +/- %0.4f' % (d, e, mf, mean, std))

max_depth: 1 / n_estimators: 1 / sqrt ->  0.4525  +/- 0.0888
max_depth: 1 / n_estimators: 1 / log2 ->  0.5578  +/- 0.0806
max_depth: 1 / n_estimators: 1 / None ->  0.5217  +/- 0.0615
max_depth: 1 / n_estimators: 5 / sqrt ->  0.5875  +/- 0.0830
max_depth: 1 / n_estimators: 5 / log2 ->  0.5983  +/- 0.1104
max_depth: 1 / n_estimators: 5 / None ->  0.5567  +/- 0.1088
max_depth: 1 / n_estimators: 10 / sqrt ->  0.6600  +/- 0.0947
max_depth: 1 / n_estimators: 10 / log2 ->  0.6795  +/- 0.0696
max_depth: 1 / n_estimators: 10 / None ->  0.6695  +/- 0.1167
max_depth: 1 / n_estimators: 50 / sqrt ->  0.6783  +/- 0.0709
max_depth: 1 / n_estimators: 50 / log2 ->  0.7106  +/- 0.0629
max_depth: 1 / n_estimators: 50 / None ->  0.6953  +/- 0.1066
max_depth: 1 / n_estimators: 100 / sqrt ->  0.7199  +/- 0.0517
max_depth: 1 / n_estimators: 100 / log2 ->  0.7264  +/- 0.0769
max_depth: 1 / n_estimators: 100 / None ->  0.6953  +/- 0.1066
max_depth: 3 / n_estimators: 1 / sqrt ->  0.5224  +/- 0.1153
max_depth: 3

In [428]:
from sklearn.ensemble import AdaBoostClassifier

param_max_depth = [1, 3, 5, 10, 50, 100, None]
param_n_estimators = [1, 5, 10, 50, 100]
for d in param_max_depth:
    for e in param_n_estimators:
        clf_tr = DecisionTreeClassifier(criterion = 'entropy', max_depth = d)
        pipe_ada = Pipeline([('scaler', StandardScaler()),
                            ('clf', AdaBoostClassifier(base_estimator = clf_tr, n_estimators = e, learning_rate = 0.01, random_state = 0))])
        cvs = cross_val_score(pipe_ada, women_X, y = women_y, cv = 10)
        mean = np.mean(cvs)
        std = np.std(cvs)
        print('max_depth: %s / n_estimators: %s ->  %0.4f  +/- %0.4f' % (d, e, mean, std))

max_depth: 1 / n_estimators: 1 ->  0.5184  +/- 0.0579
max_depth: 1 / n_estimators: 5 ->  0.5841  +/- 0.0866
max_depth: 1 / n_estimators: 10 ->  0.6447  +/- 0.1073
max_depth: 1 / n_estimators: 50 ->  0.7264  +/- 0.0838
max_depth: 1 / n_estimators: 100 ->  0.7264  +/- 0.0838
max_depth: 3 / n_estimators: 1 ->  0.7455  +/- 0.0627
max_depth: 3 / n_estimators: 5 ->  0.7407  +/- 0.0666
max_depth: 3 / n_estimators: 10 ->  0.7359  +/- 0.0699
max_depth: 3 / n_estimators: 50 ->  0.7046  +/- 0.0506
max_depth: 3 / n_estimators: 100 ->  0.7086  +/- 0.0824
max_depth: 5 / n_estimators: 1 ->  0.7151  +/- 0.0858
max_depth: 5 / n_estimators: 5 ->  0.7146  +/- 0.0801
max_depth: 5 / n_estimators: 10 ->  0.7141  +/- 0.0889
max_depth: 5 / n_estimators: 50 ->  0.6948  +/- 0.1096
max_depth: 5 / n_estimators: 100 ->  0.7246  +/- 0.0837
max_depth: 10 / n_estimators: 1 ->  0.7046  +/- 0.0642
max_depth: 10 / n_estimators: 5 ->  0.6951  +/- 0.0767
max_depth: 10 / n_estimators: 10 ->  0.6956  +/- 0.0874
max_depth: 1

In [432]:
pipe_rf = Pipeline([('scaler', StandardScaler()),
                 ('clf_rf', RandomForestClassifier(criterion = 'entropy',
                                            max_depth = 10,
                                            n_estimators = 100, 
                                            max_features = 'log2',
                                            random_state = 0,
                                            n_jobs = -1))])
pipe_rf.fit(women_X, women_y)
np.mean(cross_val_score(pipe_rf, women_X, y = women_y, cv = 10))

0.76521303258145368

## Save

In [438]:
import pickle

woman_data = {'X': women_X, 'y': women_y}

f = open('woman_data.pkl', 'wb')
pickle.dump(woman_data, f)
f.close()

In [437]:
f = open('woman_cl.pklf', 'wb')
pickle.dump(pipe_rf, f)
f.close()

In [435]:
men_X.columns

Index(['accessory_ring', 'participation', 'grade', 'drowsiness',
       'glasses_안경착용', 'phonecase', 'after_finish_lecture_강의실나감'],
      dtype='object')

In [436]:
women_X.columns

Index(['exit_no', 'how_wear_accessory', 'position_전방', 'phone_position_화면아래',
       'drowsiness', 'accessory_ring', 'campus_style_편안한복장', 'color_yes'],
      dtype='object')

# Input Step

In [1]:
sex = input('상대의 성별이 어떻게 되십니까? (1: 남성, 2: 여성)   ')
while sex not in ['1', '2']:
    print('잘못 입력 하셨습니다. 다시 입력해 주십시오.')
    sex = input('상대의 성별이 어떻게 되십니까? (1: 남자, 2: 여자)   ')
    
if sex == '1':
    print('target: 남성')
    data = dict()
    for t in men_X.columns:
        data[t] = data.get(t, 0)
    print('\n')
    
    grade = input('대상의 학년이 어떻게 됩니까? (1: 1학년, 2: 2학년, 3: 3학년, 4: 4학년)   ')
    while grade not in ['1', '2', '3', '4']:
        print('잘못 입력 하셨습니다. 다시 입력해 주십시오.')
        grade = input('대상의 학년이 어떻게 됩니까? (1: 1학년, 2: 2학년, 3: 3학년, 4: 4학년)   ')

    grade = int(grade)
    data['grade'] = grade
    print('\n')

    absent_no = input('대상이 최근 2주 이내 지각 또는 결석없이 강의를 들으러 왔습니까? (0: 아니오, 1: 예)   ')
    while absent_no not in ['0', '1']:
        print('잘못 입력 하셨습니다. 다시 입력해 주십시오.')
        absent_no = input('대상이 최근 2주 이내 지각 또는 결석없이 강의를 들으러 왔습니까? (0: 아니오, 1: 예)   ')

    if absent_no == '1':
        data['absent_no'] = 1
    print('\n')
 
    participation = input('대상이 강의에 적극적으로 참여하나요? (1: 매우아니다, 2: 아니다, 3: 보통이다, 4: 그렇다, 5: 매우그렇다)   '   )
    while participation not in ['1', '2', '3', '4', '5']:
        print('잘못 입력 하셨습니다. 다시 입력해 주십시오.')
        participation = input('대상이 강의에 적극적으로 참여하나요? (1: 매우아니다, 2: 아니다, 3: 보통이다, 4: 그렇다, 5: 매우그렇다)   '   )

    participation = int(participation)
    data['participation'] = participation
    print('\n')
    
    why_use_phone = input('대상이 강의 도중 핸드폰을 사용하나요? (0: 아니오, 1: 예)   ')
    while why_use_phone not in ['0', '1']:
        print('잘못 입력 하셨습니다. 다시 입력해 주십시오.')
        why_use_phone = input('대상이 최근 2주 이내 지각 또는 결석없이 강의를 들으러 왔습니까? (0: 아니오, 1: 예)   ')

    if why_use_phone == '1':
        data['why_use_phone'] = 1
    print('\n')

    after_finish_lecture = input('대상이 강의 끝난 직후 보인 행동이 어떻습니까? (0: 해당 없음, 1: 강의실 나감, 2: 휴대폰 사용)   ')
    while after_finish_lecture not in ['0', '1', '2']:
        print('잘못 입력 하셨습니다. 다시 입력해 주십시오.')
        after_finish_lecture = input('대상이 강의 끝난 직후 보인 행동이 어떻습니까? (0: 해당 없음, 1: 강의실 나감, 2: 휴대폰 사용)   ')

    if after_finish_lecture == '1':
        data['after_finish_lecture_강의실나감'] = 1

    if after_finish_lecture == '2':
        data['after_finish_lecture_휴대폰사용'] = 1
    print('\n')
 
    accessory = input('대상이 반지를 끼고 있나요? (0: 아니오, 1: 예)   ')
    while accessory not in ['0', '1']:
        print('잘못 입력 하셨습니다. 다시 입력해 주십시오.')
        accessory = input('대상이 반지를 끼고 있나요? (0: 아니오, 1: 예)   ')

    if accessory == '1':
        data['accessory_ring'] = 1
    print('\n')
 
    accessory = input('대상이 귀걸이를 끼고 있나요? (0: 아니오, 1: 예)   ')
    while accessory not in ['0', '1']:
        print('잘못 입력 하셨습니다. 다시 입력해 주십시오.')
        accessory = input('대상이 귀걸이를 끼고 있나요? (0: 아니오, 1: 예)   ')

    if accessory == '1':
        data['accessory_earring'] = 1
    print('\n')

    phonecase = input('대상이 핸드폰 케이스를 사용하고 있나요? (0: 아니오, 1: 예)   ')
    while phonecase not in ['0', '1']:
        print('잘못 입력 하셨습니다. 다시 입력해 주십시오.')
        phonecase = input('대상이 핸드폰 케이스를 사용하고 있나요? (0: 아니오, 1: 예)   ')

    if phonecase == '1':
        data['phonecase'] = 1
else:
    print('target: 여성')
    data = dict()
    for t in women_X.columns:
        data[t] = data.get(t, 0)
    print('\n')

    lecture = input('대상이 이번학기에 몇개의 교양 강의를 듣고 있습니까? (1: 듣지 않음, 2: 1개, 3: 2개, 4: 3개 이상)   ')
    while lecture not in ['1', '2', '3', '4']:
        print('잘못 입력 하셨습니다. 다시 입력해 주십시오.')
        lecture = input('대상이 이번학기에 몇개의 교양 강의를 듣고 있습니까? (1: 듣지 않음, 2: 1개, 3: 2개, 4: 3개 이상)   ')

    lecture = int(lecture)
    data['lecture'] = lecture
    print('\n')

    exit_no = input('대상이 최근 2주 이내 강의 도중 강의실을 나온적이 있습니까? (0: 아니오, 1: 예)   ')
    while exit_no not in ['0', '1']:
        print('잘못 입력 하셨습니다. 다시 입력해 주십시오.')
        exit_no = input('대상이 최근 2주 이내 강의 도중 강의실을 나온적이 있습니까? (0: 아니오, 1: 예)   ')

    if exit_no == '0':
        data['exit_no'] = 1
    print('\n')

    drowsiness = input('대상이 강의 도중 자주 졸고 있습니까? (1: 매우아니다, 2: 아니다, 3: 보통이다, 4: 그렇다, 5: 매우그렇다)   ')
    while drowsiness not in ['1', '2', '3', '4', '5']:
        print('잘못 입력 하셨습니다. 다시 입력해 주십시오.')
        drowsiness = input('대상이 강의 도중 자주 졸고 있습니까? (1: 매우아니다, 2: 아니다, 3: 보통이다, 4: 그렇다, 5: 매우그렇다)   ')

    drowsiness = int(drowsiness)
    data['drowsiness'] = drowsiness
    print('\n')

    position = input('대상이 강의실 내 어느 위치에 앉아 있습니까? (1: 전방, 2: 중앙, 3: 후방)   ')
    while position not in ['1', '2', '3']:
        print('잘못 입력 하셨습니다. 다시 입력해 주십시오.')
        position = input('대상이 강의실 내 어느 위치에 앉아 있습니까? (1: 전방, 2: 중앙, 3: 후방)   ')

    if position == '1':
        data['position_전방'] = 1  
    print('\n')

    attention = input('대상의 시선이 어느 방향을 주로 바라보고 있습니까? (1: 좌전방, 2: 전방, 3: 우전방)   ')
    while attention not in ['1', '2', '3']:
        print('잘못 입력 하셨습니다. 다시 입력해 주십시오.')
        attention = input('대상의 시선이 어느 방향을 주로 바라보고 있습니까? (1: 좌전방, 2: 전방, 3: 우전방)   ')

    if attention == '1':
        data['attention_좌전방'] = 1      
    print('\n')

    after_finish_lecture = input('대상이 강의 끝난 직후 보인 행동이 어떻습니까? (0: 해당 없음, 1: 강의실 나감, 2: 휴대폰 사용)   ')
    while after_finish_lecture not in ['0', '1', '2']:
        print('잘못 입력 하셨습니다. 다시 입력해 주십시오.')
        after_finish_lecture = input('대상이 강의 끝난 직후 보인 행동이 어떻습니까? (0: 해당 없음, 1: 강의실 나감, 2: 휴대폰 사용)   ')

    if after_finish_lecture == '1':
        data['after_finish_lecture_강의실나감'] = 1
    if after_finish_lecture == '2':
        data['after_finish_lecture_휴대폰사용'] = 1
    print('\n')

    glasses = input('대상이 안경 또는 렌즈를 착용 중 입니까? (0: 착용안함, 1: 안경착용, 2: 렌즈착용)   ')
    while glasses not in ['0', '1', '2']:
        print('잘못 입력 하셨습니다. 다시 입력해 주십시오.')
        glasses = input('대상이 안경 또는 렌즈를 착용 중 입니까? (0: 착용안함, 1: 안경착용, 2: 렌즈착용)   ')

    if glasses == '1':
        data['glasses_안경착용'] = 1  
    if glasses == '2':
        data['glasses_렌즈착용'] = 1     
    print('\n')

    accessory = input('대상이 팔찌를 끼고 있나요? (0: 아니오, 1: 예)   ')
    while accessory not in ['0', '1']:
        print('잘못 입력 하셨습니다. 다시 입력해 주십시오.')
        accessory = input('대상이 팔찌를 끼고 있나요? (0: 아니오, 1: 예)   ')

    if accessory == '1':
        data['accessory_bracelet'] = 1
    print('\n')

    color_yes = input('대상이 무채색의 옷을 자주 입습니까? (0: 아니오, 1: 예)   ')
    while color_yes not in ['0', '1']:
        print('잘못 입력 하셨습니다. 다시 입력해 주십시오.')
        color_yes = input('대상이 무채색의 옷을 자주 입습니까? (0: 아니오, 1: 예)   ')

    if color_yes == '0':
        data['color_yes'] = 1   
    print('\n')
    
test = pd.DataFrame([data])
print('\n')

상대의 성별이 어떻게 되십니까? (1: 남성, 2: 여성)   1
target: 남성


NameError: name 'men_X' is not defined

# Output Step

In [12]:
if sex == '1':
    if men_clf.predict(test) == 'solo':
        print('대상은 현재 솔로입니다. 용기를 내어보세요!')
    else:
        print('대상이 현재 연애 중 일지도 모릅니다. 하지만 용기내어 다가가 보세요!')    
else:
    if women_clf.predict(test) == 'solo':
        print('대상은 현재 솔로입니다. 용기를 내어보세요!')
    else:
        print('대상이 현재 연애 중 일지도 모릅니다. 하지만 용기내어 다가가 보세요!')

대상은 현재 솔로입니다. 용기를 내어보세요!


In [13]:
input('If you want to exit this page, please press the enter key.')

If you want to exit this page, please press the enter key.


''